#!/usr/bin/env bash
# Queiry web domains

display_info () {
  domain=$1
  subdomain=$2
  
  dig_output=$(dig $subdomain.$domain +short)
  
  record_type=$(echo "$dig_output" | awk 'NR==1 {print $4}')
  destination=$(echo "$dig_output" | awk 'NR==2 {print $1}')
  # Print the output in the specified format
  echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Check if the domain argument is provided
if [ -z "$1" ]; then
  echo "Please provide a domain name as an argument"
  exit 1
fi

# Check if the subdomain argument is provided
if [ -z "$2" ]; then
  # If not, display information for the default subdomains
  display_info $1 www
  display_info $1 lb-01
  display_info $1 web-01
  display_info $1 web-02
else
  # If yes, display information for the specified subdomain
  display_info $1 $2
fi
