#!/usr/bin/env bash
# transfer  file accross network

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw "Nginx HTTP"
sudo sh -c 'echo "Hello world!" > /var/www/html/index.nginx-debian.html'
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
}" > /etc/nginx/sites-available/default
service nginx start
