#!/usr/bin/env bash
# transfer  file accross network

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw "Nginx HTTP"
echo "Hello world!" > /var/www/html/index.html
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
}" > /etc/nginx/sites-available/default
sudo service nginx reload
