#!/usr/bin/env bash
# transfer  file accross network

if [[ $# -lt 4 ]]; then
        echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
        exit 1
fi

name_file=$1
ip_s=$2
usr_name=$3
ssh_dr=$4

scp -o StrictHostKeyChecking=no -i "$ssh_dr" "$name_file" "$usr_name@$ip_s":~/
