#!/usr/bin/env bash
# moves web page

sudo apt-get update
sudo apt-get install -y nginx
sudo sh -c 'echo "Hello world!" > /var/www/html/index.nginx-debian.html'
string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Pumelela-Banca permanent;"
sudo sed -i "s/server_name _;/$string/" /etc/nginx/sites-enabled/default
sudo service nginx restart 
