#!/usr/bin/env bash
# page not found

sudo apt-get update
sudo apt-get install -y nginx
sudo sh -c 'echo "Hello world!" > /var/www/html/index.nginx-debian.html'
string="server_name _;\n\trewrite ^\/redirect_me https:\\www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$string/" /etc/nginx/sites-enabled/default
sudo service enginx restart 
