#!/usr/bin/env bash
# creates copy of web-1

#install nginx
sudo apt-get update
sudo apt-get install -y nginx

# create index html
sudo sh -c 'echo "Hello world!" > /var/www/html/index.nginx-debian.html'

# add redirection
string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Pumelela-Banca permanent;"
sudo sed -i "s/server_name _;/$string/" /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" > /var/www/html/404.html

# redirection
string2="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string2/" /etc/nginx/sites-enabled/default
sudo sed -i "/server_name _;/a add_header X-Served-By 276515-web-01;" /etc/nginx/sites-enabled/default

sudo nginx -t
sudo service nginx restar
