#!/usr/bin/env bash
# configures the load balancer

apt-get update
apt-get install -y haproxy


echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo mv /etc/haproxy/haproxy.cfg{,.original}
sudo touch /etc/haproxy/haproxy.cfg

echo "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000

listen new
    bind *:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 276515-web-01 52.91.160.96:80 check
    server 276515-web-02 54.83.136.225:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy start
