#!/usr/bin/env bash
#prints 9 times and on ten also print hi

name="Best School"
other="Hi"
i=1

while [[ $(i) -le 10 ]]; do
	if [[ $(i) -eq 9 ]]; then
		echo "$name"
		echo "$other"
	else
		echo "$name"
	fi
	((i++))
done
