#!/usr/bin/env bash
# prints words at different times

fi="bad luck"
eith="good luck"
norm="Best School"
i=1

while [ $i -lt 11 ]; do
	if [ $i -eq 4 ]; then
		echo $fi
	elif [ $i -eq 8 ]; then
		echo $eith
	else
		echo $norm
	fi
	((i++))
done
