#!/usr/bin/env bash
#prints 1-20 with words at some places

i=1
italy="bad luck from China"
jap="bad luck from Japan"
cn="bad luck from Japan"

while [ $i -le 20 ]; do
	if [ $i -eq 4 ]; then
		echo $i
		echo $italy
	elif [ $i -eq 9 ]; then
		echo $i
		echo $jap
	elif [ $i -eq 17 ]; then
		echo $i
		echo $cn
	else
		echo $i
	fi
	((i++))
done
