#!/usr/bin/env bash
#print time minutes and hours
min=1
hour=0
echo "Hour: $hour"
while [[ $hour -le 11 ]]; do
	echo "$min"
	((min++))
	if [[ "$min" -eq 60 ]]; then
		min=1
		((hour++))
		echo "Hour: $hour"
	fi
done
